// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWYl8zUsEXxSbBpM_6HBFuq52uzwAM00',
    appId: '1:143715742191:web:6df1e47144408bdd7f861a',
    messagingSenderId: '143715742191',
    projectId: 'quickcart-261ef',
    authDomain: 'quickcart-261ef.firebaseapp.com',
    storageBucket: 'quickcart-261ef.appspot.com',
    measurementId: 'G-8DNLGP2YZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMRaA7_3nSDHDPsg6joD55R9f-hqh8kvg',
    appId: '1:143715742191:android:a5ca839af816c67b7f861a',
    messagingSenderId: '143715742191',
    projectId: 'quickcart-261ef',
    storageBucket: 'quickcart-261ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCI2frk1Z-9RGWTzFxOr0ab6o8as_Po9s',
    appId: '1:143715742191:ios:f9034b3a77fb4af57f861a',
    messagingSenderId: '143715742191',
    projectId: 'quickcart-261ef',
    storageBucket: 'quickcart-261ef.appspot.com',
    iosClientId: '143715742191-evee8eraal7o5k76t9qhp7efk851usdm.apps.googleusercontent.com',
    iosBundleId: 'com.quickcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCI2frk1Z-9RGWTzFxOr0ab6o8as_Po9s',
    appId: '1:143715742191:ios:8d3d0c28d2e0d0ef7f861a',
    messagingSenderId: '143715742191',
    projectId: 'quickcart-261ef',
    storageBucket: 'quickcart-261ef.appspot.com',
    iosClientId: '143715742191-pttvlrp5hcvsgp408r9it7eme8fn34nq.apps.googleusercontent.com',
    iosBundleId: 'com.quickcart.RunnerTests',
  );
}
